version: "3.8"

services:

  server:
    build:
      context: .
    restart: "no"
    expose:
      - 8000
      - 9000
    environment:
      HLCUP2020_DIFFICULTY: "${HLCUP2020_DIFFICULTY:?}"
      HLCUP2020_DURATION: "${HLCUP2020_DURATION:?}"
      HLCUP2020_START_TIMEOUT: "${HLCUP2020_START_TIMEOUT:?}"
  prometheus:
    build:
      context: ./prometheus
    expose:
      - 9090
    depends_on:
     - server
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
